#cloud-config
password: ${password} 
users:
  - almalinux
chpasswd:
  expire: false
  users:
    - name: root
      password: ${root_password} 
      type: text
    - name: almalinux
      password: ${password} 
      type: text
ssh_pwauth: false
ssh_authorized_keys:
  - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPfrqgr75qjcfc1AcjIXUfTusLGGeKfq7D++r5TVVS2rzKnO1nLHvTKPFDNEjsIvrWZVrsWPA+Y+4gXqFsmDacc=
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: true
runcmd:
  - hostnamectl hostname ${hostname}
  - setenforce 0
  - sed -i -e 's/^\SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
  - sed -i -e 's/^\#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
  - rpm -Uvh https://repo.zabbix.com/zabbix/7.0/alma/9/x86_64/zabbix-release-7.0-2.el9.noarch.rpm
  - dnf clean all
  - dnf install -y glibc-langpack-ja
  - localectl set-locale LANG=ja_JP.utf8
  - dnf install -y zabbix-server-pgsql zabbix-web-pgsql zabbix-nginx-conf zabbix-sql-scripts zabbix-selinux-policy zabbix-agent
  - dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  - dnf install -y postgresql15-server
  - postgresql-setup --initdb
  - PGSETUP_INITDB_OPTIONS='--encoding=UTF-8 --no-locale' postgresql-15-setup initdb
  - systemctl enable postgresql-15
  - systemctl start postgresql-15
  - sudo -u postgres psql -c "create user zabbix password 'zabbix';"
  - sudo -u postgres createdb -O zabbix zabbix
  - zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix
  - sed -i "s/# DBPassword=/DBPassword=zabbix/g" /etc/zabbix/zabbix_server.conf 
  - sed -i "s/#        listen          8080;/        listen          8080;/g" /etc/nginx/conf.d/zabbix.conf
  - systemctl restart zabbix-server zabbix-agent nginx php-fpm
  - systemctl enable zabbix-server zabbix-agent nginx php-fpm
  - grubby --update-kernel ALL --args selinux=0
  - echo "hoge" >> /root/hoge
  - reboot
